version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "home-assistant/builder*"
- package-ecosystem: "github-actions"
  directories:
    - "/actions/*"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
