name: "Home Assistant builder"
description: "Multi-purpose cross-compile docker builder"
inputs:
  args:
    description: "Arguments passed to the builder"
    required: true
    default: "--help"
  pull:
    description: "Pull the latest version of builder (set to `false` for testing)"
    required: false
    default: "true"
  image:
    description: "Define the builder image archictecture (default: amd64)"
    required: false
    default: "amd64"
  namespace:
    description: "Define alternative namespace to use when image not found at this repository"
    required: true
    default: "home-assistant"
runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: "v2.5.3"

    - shell: bash
      id: version
      run: |
        input=$(echo "${{ github.action_path }}" | rev | cut -d"/" -f1 | rev)
        if [[ "${input}" == "master" ]] || [[ -z "${input}" ]]; then
          input="latest"
        fi
        echo "version=${input}" >> "$GITHUB_OUTPUT"

    - shell: bash
      id: namespace
      run: |
        if docker manifest inspect ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}-builder:${{ steps.version.outputs.version }}
        then
          echo "namespace=${{ github.repository_owner }}" >> "$GITHUB_OUTPUT"
        else
          echo "namespace=${{ inputs.namespace }}" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      if: ${{ inputs.pull == 'true' }}
      run: |
        docker pull ghcr.io/${{ steps.namespace.outputs.namespace }}/${{ inputs.image }}-builder:${{ steps.version.outputs.version }}
        cosign verify \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity-regexp https://github.com/${{ steps.namespace.outputs.namespace }}/builder/.* \
          ghcr.io/${{ steps.namespace.outputs.namespace }}/${{ inputs.image }}-builder:${{ steps.version.outputs.version }}

    - shell: bash
      id: builder
      run: |
        builder=$(docker images ghcr.io/${{ steps.namespace.outputs.namespace }}/${{ inputs.image }}-builder:${{ steps.version.outputs.version }} -q)
        echo "id=$builder" >> "$GITHUB_OUTPUT"

    - shell: bash
      id: build
      run: |
        env > "${{ github.action_path }}/env_file"
        sed -i "/\(HOME\|TERM\|PWD\|HOSTNAME\|PATH\|SHLVL\|USER\|GOROOT\)/d" "${{ github.action_path }}/env_file"
        # Work around QEMU aarch64 bugs
        # https://github.com/tonistiigi/binfmt/issues/215#issuecomment-2613567455
        sudo sysctl kernel.randomize_va_space=0

        docker run --rm --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v ~/.docker:/root/.docker \
            -v ${{ github.workspace }}:/data \
            --env-file "${{ github.action_path }}/env_file" \
            ghcr.io/${{ steps.namespace.outputs.namespace }}/${{ inputs.image }}-builder:${{ steps.version.outputs.version }} \
            ${{ inputs.args }}

        sudo sysctl kernel.randomize_va_space=2

    - shell: bash
      id: verify
      run: |
        docker images \
          --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}" \
          --filter reference="*/*" \
          --filter reference="*" \
          --filter since=${{ steps.builder.outputs.id }}
branding:
  icon: "home"
  color: "blue"
