name: "Home Assistant builder"
description: "Multi-purpose cross-compile docker builder"
inputs:
  args:
    description: "Arguments passed to the builder"
    required: true
    default: "--help"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: version
      run: |
        input=$(echo "${{ github.action_path }}" | cut -d"/" -f8 )
        if [[ "${input}" == "master" ]] || [[ -z "${input}" ]]; then
          input="latest"
        fi
        echo "::set-output name=version::${input}"

    - shell: bash
      run: docker pull ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}

    - shell: bash
      run: |
        mkdir -p "${{ github.action_path }}/bin"
        curl -Lo "${{ github.action_path }}/bin/vcn" https://github.com/vchain-us/vcn/releases/download/v0.9.6/vcn-v0.9.6-linux-amd64-static
        chmod a+x "${{ github.action_path }}/bin/vcn"
        echo "${{ github.action_path }}/bin" >> $GITHUB_PATH

        if ! "${{ github.action_path }}/bin/vcn" authenticate --org home-assistant.io --silent docker://ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}; then
          echo "Invalid signature!"
          exit 1
        fi

    - shell: bash
      id: builder
      run: |
        builder=$(docker images ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} -q)
        echo "::set-output name=id::$builder"

    - shell: bash
      id: build
      run: |
        docker run --rm --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v ~/.docker:/root/.docker \
            -v ${{ github.workspace }}:/data \
            ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} \
            ${{ inputs.args }}

    - shell: bash
      id: verify
      run: |
        docker images \
          --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}" \
          --filter reference="*/*" \
          --filter reference="*" \
          --filter since=${{ steps.builder.outputs.id }}
branding:
  icon: "home"
  color: "blue"
