name: "Home Assistant builder"
description: "Multi-purpose cross-compile docker builder"
inputs:
  args:
    description: "Arguments passed to the builder"
    required: true
    default: "--help"
runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
      with:
        cosign-release: "v2.0.2"

    - shell: bash
      id: version
      run: |
        input=$(echo "${{ github.action_path }}" | rev | cut -d"/" -f1 | rev)
        if [[ "${input}" == "master" ]] || [[ -z "${input}" ]]; then
          input="latest"
        fi
        echo "version=${input}" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        docker pull ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}
        cosign verify \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity-regexp https://github.com/home-assistant/builder/.* \
          ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}

    - shell: bash
      id: builder
      run: |
        builder=$(docker images ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} -q)
        echo "id=$builder" >> "$GITHUB_OUTPUT"

    - shell: bash
      id: build
      run: |
        env > "${{ github.action_path }}/env_file"
        sed -i "/\(HOME\|TERM\|PWD\|HOSTNAME\|PATH\|SHLVL\|USER\|GOROOT\)/d" "${{ github.action_path }}/env_file"

        docker run --rm --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v ~/.docker:/root/.docker \
            -v ${{ github.workspace }}:/data \
            --env-file "${{ github.action_path }}/env_file" \
            ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} \
            ${{ inputs.args }}

    - shell: bash
      id: verify
      run: |
        docker images \
          --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}" \
          --filter reference="*/*" \
          --filter reference="*" \
          --filter since=${{ steps.builder.outputs.id }}
branding:
  icon: "home"
  color: "blue"
