image: "ghcr.io/home-assistant/{arch}-builder"
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  i386: "ghcr.io/home-assistant/i386-base:3.18"
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/builder/.*
args:
  YQ_VERSION: "v4.13.2"
  COSIGN_VERSION: "2.0.2"
labels:
  io.hass.type: builder
  org.opencontainers.image.title: "Home Assistant Builder"
  org.opencontainers.image.description: "Container-based build system for Home Assistant"
  org.opencontainers.image.source: "https://github.com/home-assistant/builder"
  org.opencontainers.image.authors: "The Home Assistant Authors"
  org.opencontainers.image.url: "https://www.home-assistant.io/"
  org.opencontainers.image.documentation: "https://developers.home-assistant.io/"
  org.opencontainers.image.licenses: "Apache License 2.0"
