name: 'Publish dev'

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture:
          - aarch64
          - amd64
          - armv7
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: homeassistant
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish builder
      uses: home-assistant/builder@master
      with:
        args: |
          --${{ matrix.architecture }} \
          --target /data \
          --generic dev